### ISSUE TITLE
vict-10: [Basic Create] - Improve working with date and time (4h)

### ISSUE THREAD

**Issue by makskostyshen** [makskostyshen/totalVictory#19]
This task involves improving program by enhancing date & time functionality:
- Change CaseListingDto DTO:
  - rename it to CaseDto
  - refactor date format from 2023-11-16 to 16.11.2023

- Create new DTO:
  - create CaseDetailsDto with all fields from CaseDto except 'currentStageDeadline'
  - create field deadlineDate with type String
  - create field deadlineTime with type String

- Improve page cases/new:
  - use CaseDetailsDto instead of CaseDto
  - split input 'Дата і час' into two inputs of equal size on layout: 'Дата' and 'Час' of types 'data' and 'time'
  - make sure widgets for date and time inputs are added

Acceptance criteria:
- CaseListingDtoIsRenamed
- CaseDetailsDto is created and used where it is needed
- When creating case, date and time parameters are set separately
- There are widgets for setting date and time on the page
- other functional is not broken

**Comment by Ratchet34702** [comment]
worked 3h 30m 

- could have been 1 hour (:

**Comment by makskostyshen** [comment]
@Ratchet34702 some changes are needed. Could have been more careful)

Please also link the Pull Request to Issue - it would be much more convenient for me to review the task

**Comment by makskostyshen** [comment]
worked 15m:
- tech review and test

**Comment by makskostyshen** [comment]
@Ratchet34702 here is another small feedback)

**Comment by makskostyshen** [comment]
worked 15m:
- tech review and test

**Comment by Ratchet34702** [comment]
worked 40 m:

- fixed sending data
- added sepparate labels for fields
- link pull request

**Comment by Ratchet34702** [comment]
worked 5 m:

- remove "required" from date and time fields

**Comment by makskostyshen** [comment]
worked 2m:
- review
