### ISSUE TITLE
vict-3: [Basic Create] - Create a redirect to case creation page (2h)

### ISSUE THREAD

**Issue by makskostyshen** [makskostyshen/totalVictory#5]
Create a button for redirect to cases creation page:
- Name of button: "Нова справа"
- Button is located on the top right part of screen, above to cases table
- Styles take from theme: [https://bootstrapmade.com/demo/NiceAdmin/](https://bootstrapmade.com/demo/NiceAdmin/)
- Path of creation page: **/cases/new**

Acceptance criteria:
- cases listing page is modified to have a button
- this button redirects to case creation page with proper address

**Comment by Ratchet34702** [comment]
Worked 1 hour

**Comment by Ratchet34702** [comment]
Worked 2 hours

**Comment by makskostyshen** [comment]
worked 15m

**Comment by makskostyshen** [comment]
@Ratchet34702 good. minor fix in PR

**Comment by makskostyshen** [comment]
good job!
