### ISSUE TITLE
vict-5: [Basic Create] - Implement sending data after case creation in front (8h)

### ISSUE THREAD

**Issue by makskostyshen** [makskostyshen/totalVictory#7]
Modify create case page functionality:
- Create POST method in controller:
    - now it just prints case in console
- Data from form is sent to POST: **/cases/new** by clicking button "Створити".
- Validation is added:
    - "**JUDGE**", "**NUMBER**", "**OPPONENT**", "**SUBJECT**" fields cannot be empty
    - validation is implemented like in theme: [https://bootstrapmade.com/demo/NiceAdmin/](https://bootstrapmade.com/demo/NiceAdmin/)
    - After creation of case redirect to listing

Acceptance criteria:
- dummy POST method is created
- data is passed to POST method of controller
- validation is implemented
- after creation of case there is a redirect to listing

**Comment by Ratchet34702** [comment]
worked 5h 30m

**Comment by makskostyshen** [comment]
worked 1h 30m:
- investigate cyrillic problems
- fix description in tasks

**Comment by makskostyshen** [comment]
@Ratchet34702 please add a pull request to task)

**Comment by Ratchet34702** [comment]
worked 5m:

- link pull request

**Comment by makskostyshen** [comment]
worked 30m:
- review
- think about further tasks

**Comment by makskostyshen** [comment]
@Ratchet34702 good job. There are only minor style fixes

**Comment by makskostyshen** [comment]
great) moving forward

**Comment by makskostyshen** [comment]
worked 5m
