### ISSUE TITLE
vict-4: [Basic Create] - Create layout for creating cases (8h)

### ISSUE THREAD

**Issue by makskostyshen** [makskostyshen/totalVictory#9]
Create a layout for creating new cases page:
- It is accessible by path **/cases/new**
- It uses layout from theme: [https://bootstrapmade.com/demo/NiceAdmin/](https://bootstrapmade.com/demo/NiceAdmin/):
- Input of data:
    - **card** class is used
    - Header in the card: "Створити нову справу"
    - For fields "**CURRENT_STAGE**", "**STAGE_DEADLINE**", "**JUDGE**", "**NUMBER**", "**OPPONENT**", "**SUBJECT**", "**CLIENT**", "**NOTE**" there are text inputs
    - For field "**DONE_WORK**" there is a text area input
- In the bottom there are 2 buttons:
    - "Назад" - redirect to listing page
    - "Створити" - redirect to listing page too

Acceptance criteria:
- layout of page is created
- page is accessible from correct path
- data is not sent anywhere controller yet

**Comment by makskostyshen** [comment]
worked 15m:
- tech review
- test

**Comment by Ratchet34702** [comment]
worked 7h:

- fix problems
- add rocker body

**Comment by makskostyshen** [comment]
worked 1h 30m:
- investigate problems with encoding
